title: MTG vs YGO: Why
author: MEEEEEEEE
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A lengthy and detailed discussion on MTG vs YGO. Purely for work related purposes.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
